#!/bin/bash

brew update
brew install trash
brew install tree
brew install tmux
brew install fd
brew install pyenv
echo 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.zshrc
